analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6568206
  brandStrength: 0.2379162
  lightness: 0.3646616
  brandColors:
    - '#0B050B'
    - '#534330'
    - '#BD9178'
    - '#CFC4B5'
    - '#88775C'
  rhythmicContrast: 0.5447325
typography_spectrum: 0.6015765599440783
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9543501
favicon: null
name: robcapilliphotography
